version: '2'
services:
  loc-nginx-proxy:
    image: dogada/loc-nginx-proxy:alpine
    container_name: loc-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
networks:
  default:
    external:
      name: webproxy
